var metrics = ["reduce", "reuse", "recycle"];
var blocks = {
    "04848db2": { reduce: 4, reuse: 5, recycle: 4, name: "I Can…Change buying habits; buy less stuff" },
    "041ac2b2": { reduce: 4, reuse: 5, recycle: 4, name: "I Can…Redefine wealth" },
    "0414c2b2": { reduce: 5, reuse: 4, recycle: 5, name: "I Can…Waterbottles, lunch boxes, bag for life" },
    "048a8db2": { reduce: 5, reuse: 4, recycle: 5, name: "I Can…Shop at plastic free shop" },
    "0421c2b2": { reduce: 4, reuse: 4, recycle: 4, name: "I Can…Lobby a business" },
    "042dc2b2": { reduce: 4, reuse: 4, recycle: 4, name: "I Can…Run a campaign at school" },
    "0427c2b2": { reduce: 4, reuse: 4, recycle: 4, name: "I Can…Talk to your MP/Councillor" },
    "040fc3b2": { reduce: 4, reuse: 4, recycle: 4, name: "I Can…Youth Strike" },
    "0439c2b2": { reduce: 5, reuse: 4, recycle: 5, name: "Policy - Supermarkets ban single-use plastics" },
    "043fc2b2": { reduce: 4, reuse: 5, recycle: 4, name: "Policy - Living wage for clothes factory workers" },
    "0445c2b2": { reduce: 4, reuse: 5, recycle: 4, name: "Policy - Living wage for UK" },
    "044bc2b2": { reduce: 4, reuse: 5, recycle: 5, name: "Policy - Food waste" },
    "04908cb2": { reduce: 5, reuse: 5, recycle: 4, name: "Policy - 4 day working week; buy less, make less, live more" },
    "0433c2b2": { reduce: 3, reuse: 5, recycle: 4, name: "Policy - Tax on Fossil Fuels and Subsidies for Renewables" },
    "04908db2": { reduce: 3, reuse: 3, recycle: 3, name: "Policy - Blank" },
    "04e5c3b2": { reduce: 1, reuse: 2, recycle: 1, name: "Incinerator" },
    "04dec3b2": { reduce: 3, reuse: 4, recycle: 5, name: "Recycle Centre" },
    "04d8c3b2": { reduce: 1, reuse: 1, recycle: 1, name: "Landfill" },
    "04d2c3b2": { reduce: 2, reuse: 1, recycle: 2, name: "Shipping waste abroad" },
    "04ccc3b2": { reduce: 1, reuse: 1, recycle: 2, name: "Mega Supermarket" },
    "04c6c3b2": { reduce: 2, reuse: 3, recycle: 2, name: "Sports Ground" },
    "04c0c3b2": { reduce: 2, reuse: 2, recycle: 2, name: "O2 Arena" },
    "041c923a": { reduce: 2, reuse: 5, recycle: 1, name: "Nature Reserve" },
    "0403c3b2": { reduce: 2, reuse: 4, recycle: 2, name: "Kirkgate Market" },
    "0422933a": { reduce: 4, reuse: 5, recycle: 4, name: "Park" },
    "041e933a": { reduce: 5, reuse: 3, recycle: 4, name: "Gym and Pool" },
    "041a933a": { reduce: 2, reuse: 2, recycle: 2, name: "Kart Track" },
    "0449933a": { reduce: 3, reuse: 4, recycle: 3, name: "Kart Track (Electric)" },
    "04ebc3b2": { reduce: 2, reuse: 4, recycle: 2, name: "Skateboard Park" },
    "047e8db2": { reduce: 4, reuse: 5, recycle: 4, name: "Allotments" },
    "049cc3b2": { reduce: 4, reuse: 5, recycle: 4, name: "Playbox" },
    "04aec3b2": { reduce: 4, reuse: 5, recycle: 4, name: "Interplay theatre" },
    "04f1c3b2": { reduce: 2, reuse: 3, recycle: 2, name: "Minimarket" },
    "045fc3b2": { reduce: 5, reuse: 5, recycle: 5, name: "Shops - Jar Tree, Charity Shop, Swap Shop" },
    "0453c3b2": { reduce: 5, reuse: 5, recycle: 5, name: "Shops - Revive, Golden Oldies" },
    "0409c3b2": { reduce: 5, reuse: 5, recycle: 4, name: "Shops - CaFaye, Toy Library, Time Bank" },
    "04b6beb2": { reduce: 1, reuse: 1, recycle: 1, name: "Shops - Car Showroom, Fast Fashion" },
    "0465c3b2": { reduce: 5, reuse: 5, recycle: 4, name: "Shops - Rainbow Junktion, Community Shop" },
    "04a4beb2": { reduce: 2, reuse: 3, recycle: 2, name: "Shops - Closed Shop, Food Bank, Loans" },
    "048ac3b2": { reduce: 5, reuse: 5, recycle: 5, name: "Shops - Bike Repair, Repair Cafe, Tool Library" },
    "0459c3b2": { reduce: 4, reuse: 5, recycle: 3, name: "Shops - Geek Retreat, Geeks Room, Escape Room" },
    "04b0beb2": { reduce: 1, reuse: 1, recycle: 1, name: "Shops - Snottee Coffee, Artisan Bakery, Apple Shop" },
    "0471c3b2": { reduce: 4, reuse: 5, recycle: 3, name: "Hackspace" },
    "044dc3b2": { reduce: 5, reuse: 5, recycle: 5, name: "SCRAP Re-use" },
    "04fdc3b2": { reduce: 5, reuse: 4, recycle: 5, name: "Seagulls" },
    "04f7c3b2": { reduce: 5, reuse: 5, recycle: 4, name: "Rent to Buy" },
    "0441933a": { reduce: 3, reuse: 3, recycle: 4, name: "Community Garden" },
    "0445933a": { reduce: 4, reuse: 4, recycle: 4, name: "Wave Power" },
    "040a933a": { reduce: 4, reuse: 5, recycle: 4, name: "Pedaller's Arms" },
    "0407923a": { reduce: 4, reuse: 5, recycle: 3, name: "LUSH" },
    "043d933a": { reduce: 1, reuse: 1, recycle: 1, name: "Rubbish Strewn Festival Site" },
    "0416933a": { reduce: 1, reuse: 1, recycle: 1, name: "Mine for phone materials" },
    "0439933a": { reduce: 1, reuse: 1, recycle: 1, name: "Advertising Billboard" },
    "0431933a": { reduce: 2, reuse: 2, recycle: 1, name: "Action - Public unsure of what can be recycled" },
    "0426933a": { reduce: 3, reuse: 3, recycle: 2, name: "Different councils recycle different stuff" },
    "042a933a": { reduce: 3, reuse: 3, recycle: 5, name: "Consistent council recycling schemes" },
    "045d933a": { reduce: 3, reuse: 3, recycle: 4, name: "Community Football Ground" },
    "0459933a": { reduce: 4, reuse: 5, recycle: 4, name: "Swap Shop" },
    "0451933a": { reduce: 4, reuse: 5, recycle: 4, name: "Mobile Repair Shop" },
    "044d933a": { reduce: 5, reuse: 5, recycle: 4, name: "Repair Cafe (standalone)" },
}
